//! The named sketch sizes are aliases of the const-generic sketch types
//! (`HyperLogLogN<M>`, `DDSketchN<BINS>`, `CountMinSketchN<W, D>`,
//! `HeavyHittersN<K, W, D>`), and each instantiation keeps its closed forms.
//!
//! * identity: every alias is the instantiation its name states (a function
//!   generic over the const parameters returns them)
//! * oracle: HyperLogLog with every register at 1 estimates `2·α_m·m`,
//!   `α_m = 0.7213 / (1 + 1.079 / m)` (raw estimator `α_m m² / Σ 2^{−ρ}`)
//! * oracle: Count-Min `error_bound = e / W`, `confidence = 1 − e^{−D}`
//! * oracle: HeavyHitters with fewer than `K` distinct keys reports all of them,
//!   exact, in descending order
//! * oracle: DDSketch `quantile(q)` (bucket lower edge) is within `2α/(1+α)`
//!   of the rank-`⌈q·n⌉` order statistic, for `q > 0` (AUD-A-S3W1-006 is the
//!   `q = 0` case) and values inside the bin range (AUD-A-S3W1-009 is the
//!   outside case)
//! * degenerate inputs: empty sketches, absent keys, non-finite values
//! * regression pin: digests of a fixed input stream, recorded from the
//!   pre-refactor code (one struct per size generated by `macro_rules!`)

use alice_physics::sketch::*;

fn hll_m<const M: usize>(_: &HyperLogLogN<M>) -> usize {
    M
}
fn dd_bins<const BINS: usize>(_: &DDSketchN<BINS>) -> usize {
    BINS
}
fn cms_wd<const W: usize, const D: usize>(_: &CountMinSketchN<W, D>) -> (usize, usize) {
    (W, D)
}
fn hh_kwd<const K: usize, const W: usize, const D: usize>(
    _: &HeavyHittersN<K, W, D>,
) -> (usize, usize, usize) {
    (K, W, D)
}

#[test]
fn every_alias_is_the_instantiation_its_name_states() {
    assert_eq!(hll_m(&HyperLogLog10::new()), 1 << 10);
    assert_eq!(hll_m(&HyperLogLog12::new()), 1 << 12);
    assert_eq!(hll_m(&HyperLogLog14::new()), 1 << 14);
    assert_eq!(hll_m(&HyperLogLog16::new()), 1 << 16);
    assert_eq!(hll_m(&HyperLogLog::new()), 1 << 14);

    assert_eq!(dd_bins(&DDSketch128::new(0.1)), 128);
    assert_eq!(dd_bins(&DDSketch256::new(0.1)), 256);
    assert_eq!(dd_bins(&DDSketch512::new(0.1)), 512);
    assert_eq!(dd_bins(&DDSketch1024::new(0.1)), 1024);
    assert_eq!(dd_bins(&DDSketch2048::new(0.1)), 2048);
    assert_eq!(dd_bins(&DDSketch::new(0.1)), 2048);

    assert_eq!(cms_wd(&CountMinSketch1024x5::new()), (1024, 5));
    assert_eq!(cms_wd(&CountMinSketch2048x7::new()), (2048, 7));
    assert_eq!(cms_wd(&CountMinSketch4096x5::new()), (4096, 5));
    assert_eq!(cms_wd(&CountMinSketch::new()), (1024, 5));

    assert_eq!(hh_kwd(&HeavyHitters5::new()), (5, 1024, 5));
    assert_eq!(hh_kwd(&HeavyHitters10::new()), (10, 1024, 5));
    assert_eq!(hh_kwd(&HeavyHitters20::new()), (20, 2048, 7));
    assert_eq!(hh_kwd(&HeavyHitters::new()), (10, 1024, 5));

    // The associated constants agree with the parameters.
    assert_eq!((HyperLogLog12::M, HyperLogLog12::P), (4096, 12));
    assert_eq!((HyperLogLog16::M, HyperLogLog16::P), (65536, 16));
    assert_eq!(DDSketch512::BINS, 512);
    assert_eq!(
        (CountMinSketch2048x7::WIDTH, CountMinSketch2048x7::DEPTH),
        (2048, 7)
    );
    assert_eq!(HeavyHitters20::K, 20);
}

fn hll_all_ones_is_two_alpha_m<const M: usize>(mut h: HyperLogLogN<M>) {
    // hash = bit 63 | idx: register idx (low P bits), first set bit of the
    // remaining 64 − P bits is the top one ⇒ ρ = 1.
    for idx in 0..M as u64 {
        h.insert_hash((1u64 << 63) | idx);
    }
    assert!(h.registers().iter().all(|&r| r == 1));
    let m = M as f64;
    let expected = 2.0 * (0.7213 / (1.0 + 1.079 / m)) * m;
    let got = h.cardinality();
    assert!(
        ((got - expected) / expected).abs() < 1e-12,
        "M={M}: {got} vs 2·α·m = {expected}"
    );
}

#[test]
fn hyperloglog_all_registers_one_is_two_alpha_m() {
    hll_all_ones_is_two_alpha_m(HyperLogLog10::new());
    hll_all_ones_is_two_alpha_m(HyperLogLog12::new());
    hll_all_ones_is_two_alpha_m(HyperLogLog14::new());
    hll_all_ones_is_two_alpha_m(HyperLogLog16::new());
    // A size without a named alias uses the same law.
    hll_all_ones_is_two_alpha_m(HyperLogLogN::<256>::new());
}

fn cms_bounds<const W: usize, const D: usize>(c: &CountMinSketchN<W, D>) {
    let eps = core::f64::consts::E / W as f64;
    // e^{−D} as D divisions by e (independent of det_math::exp64)
    let conf = 1.0 - (0..D).fold(1.0f64, |acc, _| acc / core::f64::consts::E);
    assert!((c.error_bound() - eps).abs() < 1e-15, "W={W}");
    assert!((c.confidence() - conf).abs() < 1e-12, "D={D}");
}

#[test]
fn countmin_error_bound_and_confidence_closed_forms() {
    cms_bounds(&CountMinSketch1024x5::new());
    cms_bounds(&CountMinSketch2048x7::new());
    cms_bounds(&CountMinSketch4096x5::new());
    cms_bounds(&CountMinSketchN::<64, 3>::new());
}

fn hh_exact_below_k<const K: usize, const W: usize, const D: usize>(
    mut hh: HeavyHittersN<K, W, D>,
) {
    let keys = K - 1;
    // key j inserted 2j + 1 times, rounds interleave the keys
    for round in 0..2 * keys {
        for j in 0..keys {
            if round < 2 * j + 1 {
                hh.insert_hash(FnvHasher::hash_u64(7000 + j as u64));
            }
        }
    }
    let top: Vec<HeavyHitterEntry> = hh.top().copied().collect();
    let expected: Vec<HeavyHitterEntry> = (0..keys)
        .rev()
        .map(|j| HeavyHitterEntry {
            hash: FnvHasher::hash_u64(7000 + j as u64),
            count: 2 * j as u64 + 1,
        })
        .collect();
    assert_eq!(top, expected, "K={K}");
    assert_eq!(hh.cms().total(), (keys * keys) as u64, "Σ(2j+1) = keys²");
}

#[test]
fn heavy_hitters_exact_top_k_below_k_distinct_keys() {
    hh_exact_below_k(HeavyHitters5::new());
    hh_exact_below_k(HeavyHitters10::new());
    hh_exact_below_k(HeavyHitters20::new());
}

fn dd_within_edge_bound<const BINS: usize>(mut s: DDSketchN<BINS>) {
    let alpha = s.alpha();
    let n = 300u64;
    // 0.5 + 0.7·i: inside γ^(−BINS/4) .. γ^(3·BINS/4) at each size's α
    let values: Vec<f64> = (0..n).map(|i| 0.5 + 0.7 * i as f64).collect();
    for &v in values.iter().rev() {
        s.insert(v);
    }
    let bound = 2.0 * alpha / (1.0 + alpha) + 1e-12;
    for r in 1..=n {
        let q = (r as f64 - 0.5) / n as f64;
        let v = values[(r - 1) as usize];
        let rel = (s.quantile(q) - v).abs() / v;
        assert!(rel <= bound, "BINS={BINS} rank {r}: {rel} > {bound}");
    }
}

#[test]
fn ddsketch_quantile_within_edge_bound() {
    dd_within_edge_bound(DDSketch128::new(0.1));
    dd_within_edge_bound(DDSketch256::new(0.05));
    dd_within_edge_bound(DDSketch512::new(0.02));
    dd_within_edge_bound(DDSketch1024::new(0.02));
    dd_within_edge_bound(DDSketch2048::new(0.01));
}

/// Degenerate inputs: the empty HLL estimates 0 (all registers zero ⇒ linear
/// counting `m·ln(m/m)`), the empty DDSketch answers 0 for every quantile and
/// ignores NaN / ±∞, absent keys estimate 0, the empty tracker lists nothing.
#[test]
fn degenerate_inputs() {
    assert_eq!(HyperLogLog12::new().cardinality(), 0.0);
    let mut d = DDSketch512::new(0.02);
    assert_eq!(d.quantile(0.5), 0.0);
    d.insert(f64::NAN);
    d.insert(f64::INFINITY);
    d.insert(f64::NEG_INFINITY);
    assert_eq!((d.count(), d.sum()), (0, 0.0));
    assert_eq!(d.quantile(1.0), 0.0);
    assert_eq!(d.mean(), 0.0);
    let c = CountMinSketch4096x5::new();
    assert_eq!((c.estimate(&1u64), c.total()), (0, 0));
    assert_eq!(HeavyHitters20::new().top().count(), 0);
}

// ---------------------------------------------------------------------------
// Regression pin (not an oracle): the digests below were recorded by running
// these exact digest functions against the pre-refactor src/sketch.rs (one
// struct per size generated by macro_rules!). They detect any change in
// hashing, register update, bucket arithmetic or top-k ordering; they do not
// show that those values are correct (the oracles above do that).
// ---------------------------------------------------------------------------

fn fold(acc: u64, x: u64) -> u64 {
    (acc ^ x).wrapping_mul(0x0000_0100_0000_01b3)
}
const SEED: u64 = 0xcbf2_9ce4_8422_2325;

fn hll_digest<const M: usize>(mut h: HyperLogLogN<M>) -> u64 {
    for i in 0..3000u64 {
        h.insert_hash(FnvHasher::hash_u64(i));
    }
    for i in 0..500u32 {
        h.insert(&i);
    }
    for i in 0..200u16 {
        h.insert_bytes(&i.to_le_bytes());
    }
    let mut acc = SEED;
    for &r in h.registers() {
        acc = fold(acc, u64::from(r));
    }
    acc = fold(acc, h.cardinality().to_bits());
    acc = fold(acc, HyperLogLogN::<M>::M as u64);
    fold(acc, HyperLogLogN::<M>::P as u64)
}

fn dd_digest<const BINS: usize>(mut s: DDSketchN<BINS>) -> u64 {
    for i in 0..4000u64 {
        let v = ((i * 7919) % 1000) as f64 * 0.37 + 0.001;
        let v = if i % 13 == 0 {
            0.0
        } else if i % 5 == 0 {
            -v
        } else {
            v
        };
        s.insert(v);
    }
    s.insert(f64::NAN);
    s.insert(f64::INFINITY);
    let mut acc = SEED;
    acc = fold(acc, s.count());
    for x in [s.sum(), s.min(), s.max(), s.mean(), s.alpha()] {
        acc = fold(acc, x.to_bits());
    }
    for q in [0.0, 0.01, 0.1, 0.25, 0.5, 0.75, 0.9, 0.99, 1.0] {
        acc = fold(acc, s.quantile(q).to_bits());
    }
    fold(acc, DDSketchN::<BINS>::BINS as u64)
}

fn cms_digest<const W: usize, const D: usize>(mut c: CountMinSketchN<W, D>) -> u64 {
    for i in 0..20000u64 {
        c.insert_hash(FnvHasher::hash_u64(i % 700), (i % 3) + 1);
    }
    for i in 0..300u64 {
        c.insert(&i);
    }
    for i in 0..100u16 {
        c.insert_bytes(&i.to_le_bytes());
    }
    let mut acc = SEED;
    for k in 0..1000u64 {
        acc = fold(acc, c.estimate_hash(FnvHasher::hash_u64(k)));
    }
    for k in 0..50u64 {
        acc = fold(acc, c.estimate(&k));
    }
    acc = fold(acc, c.estimate_bytes(&7u16.to_le_bytes()));
    acc = fold(acc, c.total());
    acc = fold(acc, c.error_bound().to_bits());
    acc = fold(acc, c.confidence().to_bits());
    acc = fold(acc, CountMinSketchN::<W, D>::WIDTH as u64);
    fold(acc, CountMinSketchN::<W, D>::DEPTH as u64)
}

fn hh_digest<const K: usize, const W: usize, const D: usize>(mut h: HeavyHittersN<K, W, D>) -> u64 {
    for i in 0..6000u64 {
        h.insert_hash(FnvHasher::hash_u64((i * i + 3 * i) % 61));
    }
    let mut acc = SEED;
    for e in h.top() {
        acc = fold(acc, e.hash);
        acc = fold(acc, e.count);
    }
    acc = fold(acc, h.cms().total());
    acc = fold(acc, h.cms().estimate_hash(FnvHasher::hash_u64(5)));
    fold(acc, HeavyHittersN::<K, W, D>::K as u64)
}

#[test]
fn regression_pin_matches_pre_refactor_digests() {
    assert_eq!(hll_digest(HyperLogLog10::new()), 0x7a07_de5d_0610_2f04);
    assert_eq!(hll_digest(HyperLogLog12::new()), 0x6044_51d8_bc59_ff49);
    assert_eq!(hll_digest(HyperLogLog14::new()), 0xde2c_73d6_2834_1e1f);
    assert_eq!(hll_digest(HyperLogLog16::new()), 0xdf78_fe2a_686a_6827);
    assert_eq!(hll_digest(HyperLogLog::new()), 0xde2c_73d6_2834_1e1f);

    // Re-pinned with AUD-A-S3W1-006 / -009 (the digest folds quantile(0.0),
    // which is now the smallest bucket, not the outermost negative edge; and the
    // stream's 0.001 lies below the old fixed window of the 128 / 256 / 512
    // sizes, which clamped it into bucket 0). With the rank change alone
    // reverted, 1024 and 2048 — whose data fits the old window — reproduce
    // the previous digests 0x2bb9_2c6e_9423_d87d / 0xf9bc_447b_7ba3_4b2f.
    assert_eq!(dd_digest(DDSketch128::new(0.1)), 0x8f54_6624_6d75_e314);
    assert_eq!(dd_digest(DDSketch256::new(0.05)), 0xc228_dd72_fb0a_36be);
    assert_eq!(dd_digest(DDSketch512::new(0.02)), 0x10a5_004f_72c0_a6d7);
    assert_eq!(dd_digest(DDSketch1024::new(0.02)), 0x10a3_004f_72bd_40d7);
    assert_eq!(dd_digest(DDSketch2048::new(0.01)), 0xdf73_d5ae_becd_26e7);
    assert_eq!(dd_digest(DDSketch::new(0.01)), 0xdf73_d5ae_becd_26e7);

    assert_eq!(
        cms_digest(CountMinSketch1024x5::new()),
        0xa261_412d_5646_22d6
    );
    assert_eq!(
        cms_digest(CountMinSketch2048x7::new()),
        0x3afc_9c30_b0f8_650c
    );
    assert_eq!(
        cms_digest(CountMinSketch4096x5::new()),
        0xebcf_59d9_5a36_9a13
    );
    assert_eq!(cms_digest(CountMinSketch::new()), 0xa261_412d_5646_22d6);

    assert_eq!(hh_digest(HeavyHitters5::new()), 0xb80b_5daf_01c9_676b);
    assert_eq!(hh_digest(HeavyHitters10::new()), 0xe2a2_dba1_6d34_d625);
    assert_eq!(hh_digest(HeavyHitters20::new()), 0x155c_c891_efad_3b56);
    assert_eq!(hh_digest(HeavyHitters::new()), 0xe2a2_dba1_6d34_d625);
}
