#!/usr/bin/env python3
"""Per-target wall-clock timings for the in-diff mutants baseline budget.

scripts/mutants_baseline_budget.py derives the in-diff mutants baseline
timeout from measured per-target times instead of a guessed constant. This
script produces and checks the table it reads (scripts/mutants-baseline-timings.txt):
one `<target> <seconds>` line per `--lib` and per integration test target
(`tests/*.rs`, named by file stem), taken from a single `cargo nextest run`
pass with structured output (so a 450+-target crate is timed in one pass, not
one cargo invocation per target).

`--check` fails if a target that exists in the tree (a `tests/*.rs` file, or
`lib` when src/lib.rs has any `#[test]`/`#[cfg(test)]`) is missing from the
table: a new test added without a fresh table would otherwise silently use
no budget contribution for it. It does not fail on a table entry whose target
no longer exists (removed tests are harmless to leave; `--prune` drops them).

  scripts/mutants_baseline_timings.py --regenerate [--timeout SECONDS]
  scripts/mutants_baseline_timings.py --check
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TABLE = ROOT / "scripts" / "mutants-baseline-timings.txt"
HEADER = (
    "# target seconds -- generated by scripts/mutants_baseline_timings.py --regenerate\n"
    "# one cargo nextest run, lib + every tests/*.rs target; re-generate when tests/ changes\n"
)


def current_targets() -> set[str]:
    """Every target name scripts/mutants_baseline_budget.py can be asked about:
    `lib` plus the file stem of every tests/*.rs integration test target."""
    out = {"lib"}
    out |= {p.stem for p in (ROOT / "tests").glob("*.rs")}
    return out


# every optional feature that builds on the host test runner and does not
# compile a target out: everything in Cargo.toml's [features] except
# wasm/python (need a non-host target / a PyO3 extension-module build, same
# exclusion mutants_in_diff_plan.py makes) and parallel (several hyperelastic
# oracles are `#![cfg(not(feature = "parallel"))]` -- deterministic only
# single-threaded -- so turning it on compiles their test binary to zero
# tests, measured 2026-10-10: analytic_cubic_hyperelastic / _quadratic_ /
# _degenerate all report "no tests to run" under this set with parallel on).
# No test file requires parallel positively, so dropping it loses no
# coverage. One pass with the rest on measures every remaining target in a
# single run, including the ones behind a feature no single standard axis
# turns on (replay/neural/analytics/gpu-solver-bridge) -- a timing for a
# target the real job runs with fewer features is a conservative (not an
# under-) estimate.
HOST_FEATURES = "std,simd,ffi,gpu-solver-bridge,neural,replay,analytics"


def regenerate(timeout: float, features: str = HOST_FEATURES) -> dict[str, float]:
    args = ["cargo", "nextest", "run", "--no-fail-fast",
            "--message-format", "libtest-json-plus", "--lib"]
    if features:
        args += ["--features", features]
    for t in sorted(current_targets() - {"lib"}):
        args += ["--test", t]
    env = {"NEXTEST_EXPERIMENTAL_LIBTEST_JSON": "1"}
    import os
    proc = subprocess.run(args, cwd=ROOT, capture_output=True, text=True,
                           env={**os.environ, **env}, timeout=timeout)
    times: dict[str, float] = {}
    for line in proc.stdout.splitlines():
        line = line.strip()
        if not line.startswith("{"):
            continue
        try:
            d = json.loads(line)
        except ValueError:
            continue
        if d.get("type") != "suite" or d.get("event") != "ok":
            continue
        nx = d.get("nextest") or {}
        binary = nx.get("test_binary")
        if binary is None:
            continue
        # the lib target's own binary name is the crate name, not "lib"
        name = "lib" if nx.get("kind") == "lib" else binary
        times[name] = max(times.get(name, 0.0), float(d.get("exec_time", 0.0)))
    if not times:
        print("error: no suite-ok event parsed from nextest output (compared nothing)",
              file=sys.stderr)
        print(proc.stdout[-4000:], file=sys.stderr)
        print(proc.stderr[-4000:], file=sys.stderr)
        sys.exit(1)
    return times


def write_table(times: dict[str, float]) -> None:
    lines = [HEADER]
    for name in sorted(times):
        lines.append(f"{name} {times[name]:.3f}\n")
    TABLE.write_text("".join(lines), encoding="utf-8")


def read_table() -> dict[str, float]:
    out: dict[str, float] = {}
    if not TABLE.exists():
        return out
    for line in TABLE.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        name, _, secs = line.rpartition(" ")
        if not name:
            continue
        out[name] = float(secs)
    return out


def check() -> int:
    table = read_table()
    if not table:
        print("error: scripts/mutants-baseline-timings.txt is empty or missing "
              "(compared nothing)", file=sys.stderr)
        return 1
    missing = sorted(current_targets() - set(table))
    if missing:
        print(f"error: {len(missing)} target(s) exist but are not in the timing table "
              f"(stale; re-run --regenerate): {', '.join(missing[:20])}"
              + (" ..." if len(missing) > 20 else ""), file=sys.stderr)
        return 1
    print(f"ok: {len(table)} target(s) in the table, {len(current_targets())} "
          f"target(s) in the tree, none missing", file=sys.stderr)
    return 0


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--regenerate", action="store_true")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--timeout", type=float, default=2700.0,
                     help="seconds to allow the single regenerating nextest run (default 45m)")
    ap.add_argument("--prune", action="store_true",
                     help="with --regenerate, drop table entries for targets that no longer exist")
    args = ap.parse_args(argv)
    if args.regenerate:
        times = regenerate(args.timeout)
        if args.prune:
            times = {k: v for k, v in times.items() if k in current_targets()}
        write_table(times)
        print(f"wrote {len(times)} target(s) to {TABLE}", file=sys.stderr)
        return 0
    if args.check:
        return check()
    print("usage: --regenerate or --check", file=sys.stderr)
    return 2


if __name__ == "__main__":
    sys.exit(main())
